name: Docker Scout

# reusable workflow, do not add triggers
on:
  workflow_call:
  workflow_dispatch:

jobs:
  docker-scout:
    name: main
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        os:
          - linux
        arch:
          - amd64
          - arm64

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Metadata for container
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.repo_names }}
          tags: |
            type=raw,value={{sha}}

      - name: Run Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves
          only-fixed: true
          platform: ${{ matrix.os }}/${{ matrix.arch }}
          image: ${{ steps.meta.outputs.tags }}
